# Generated by Django 2.2.5 on 2020-12-15 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gakusei',
            field=models.BooleanField(default=False),
        ),
    ]
